In [1]:
import pandas as pd

all_island = pd.read_csv("../data/quarterly_all_island.csv")
roi_clean = pd.read_csv("../data/roi_quarterly_clean.csv")

In [2]:
roi_counties = [
    "Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway",
    "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick",
    "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly",
    "Roscommon", "Sligo", "Tipperary", "Waterford",
    "Westmeath", "Wexford", "Wicklow"
]

In [3]:
all_island_no_roi = all_island[
    ~all_island["County"].isin(roi_counties)
].copy()

In [4]:
quarterly_all_island_clean = pd.concat(
    [all_island_no_roi, roi_clean],
    ignore_index=True
)

In [6]:
# Row counts
print("Old all-island:", all_island.shape)
print("New all-island:", quarterly_all_island_clean.shape)

# Check RoI rows
quarterly_all_island_clean[
    quarterly_all_island_clean["County"] == "Dublin"
].head()

Old all-island: (2357, 6)
New all-island: (2357, 6)

      County  Year  Quarter   Period  transaction_count  avg_price
1013  Dublin  2010        1  2010 Q1              964.0  337164.27
1014  Dublin  2010        2  2010 Q2             1273.0  316153.25
1015  Dublin  2010        3  2010 Q3             1447.0  318730.26
1016  Dublin  2010        4  2010 Q4             1153.0  302575.21
1017  Dublin  2011        1  2011 Q1              785.0  304903.63

In [7]:

# Check NI rows still exist
quarterly_all_island_clean[
    quarterly_all_island_clean["County"] == "Belfast"
].head()

      County  Year  Quarter   Period  transaction_count    avg_price
189  Belfast  2010        1  2010 Q1              599.0  136522.8081
190  Belfast  2010        2  2010 Q2              604.0  140400.1440
191  Belfast  2010        3  2010 Q3              534.0  138804.9405
192  Belfast  2010        4  2010 Q4              606.0  124298.7005
193  Belfast  2011        1  2011 Q1              585.0  118103.5470

In [8]:
quarterly_all_island_clean.to_csv(
    "../data/quarterly_all_island.csv",
    index=False
)