In [1]:
import pandas as pd

df = pd.read_csv("../data/all_island_quarterly_inflation_clean.csv")

# Sort correctly
df = df.sort_values(["County", "Year", "Quarter"])

# Nominal price growth
df["price_qoq_pct"] = (
    df.groupby("County")["avg_price"]
      .pct_change() * 100
)

df["price_yoy_pct"] = (
    df.groupby("County")["avg_price"]
      .pct_change(4) * 100
)

# Inflation-adjusted growth (real change)
df["real_price_qoq_pct"] = df["price_qoq_pct"] - df["Inflation_Rate"]
df["real_price_yoy_pct"] = df["price_yoy_pct"] - df["Inflation_Rate"]

df.head()

,County,Year,Quarter,Period,Inflation_Rate,real_avg_price,Region,is_ni,transaction_count,avg_price,price_qoq_pct,price_yoy_pct,real_price_qoq_pct,real_price_yoy_pct
1664,Antrim and Newtownabbey,2010,1,2010 Q1,3.28,143630.65,Northern Ireland,True,217.0,148341.74,NaN,NaN,NaN,NaN
1665,Antrim and Newtownabbey,2010,2,2010 Q2,3.46,147734.48,Northern Ireland,True,245.0,152846.09,3.036468,NaN,-0.423532,NaN
1666,Antrim and Newtownabbey,2010,3,2010 Q3,3.09,152217.47,Northern Ireland,True,269.0,156920.99,2.666015,NaN,-0.423985,NaN
1667,Antrim and Newtownabbey,2010,4,2010 Q4,3.38,134301.09,Northern Ireland,True,270.0,138840.47,-11.522053,NaN,-14.902053,NaN
1668,Antrim and Newtownabbey,2011,1,2011 Q1,4.12,128956.20,Northern Ireland,True,205.0,134269.20,-3.292462,-9.486568,-7.412462,-13.606568

In [2]:
df = df.drop(columns=["real_avg_price"], errors="ignore")

In [3]:
df.to_csv(
    "../data/all_island_quarterly_inflation_clean.csv",
    index=False
)

In [5]:
df.tail(20)

,County,Year,Quarter,Period,Inflation_Rate,Region,is_ni,transaction_count,avg_price,price_qoq_pct,price_yoy_pct,real_price_qoq_pct,real_price_yoy_pct
1644,Wicklow,2021,1,2021 Q1,-0.23,Republic of Ireland,False,322.0,374010.19,7.179901,12.085106,7.409901,12.315106
1645,Wicklow,2021,2,2021 Q2,1.40,Republic of Ireland,False,268.0,363857.38,-2.714581,12.773433,-4.114581,11.373433
1646,Wicklow,2021,3,2021 Q3,2.93,Republic of Ireland,False,368.0,404732.96,11.233957,24.813869,8.303957,21.883869
1647,Wicklow,2021,4,2021 Q4,5.27,Republic of Ireland,False,370.0,376868.13,-6.884744,7.998899,-12.154744,2.728899
1648,Wicklow,2022,1,2022 Q1,5.77,Republic of Ireland,False,258.0,389030.02,3.227094,4.015888,-2.542906,-1.754112
1649,Wicklow,2022,2,2022 Q2,7.97,Republic of Ireland,False,298.0,425259.77,9.312842,16.875400,1.342842,8.905400
1650,Wicklow,2022,3,2022 Q3,8.70,Republic of Ireland,False,346.0,425647.30,0.091128,5.167442,-8.608872,-3.532558
1651,Wicklow,2022,4,2022 Q4,8.80,Republic of Ireland,False,343.0,459546.54,7.964162,21.938286,-0.835838,13.138286
1652,Wicklow,2023,1,2023 Q1,7.97,Republic of Ireland,False,252.0,414454.09,-9.812379,6.535246,-17.782379,-1.434754
1653,Wicklow,2023,2,2023 Q2,6.63,Republic of Ireland,False,298.0,438707.21,5.851823,3.162171,-0.778177,-3.467829
1654,Wicklow,2023,3,2023 Q3,6.23,Republic of Ireland,False,374.0,416903.03,-4.970098,-2.054346,-11.200098,-8.284346
1655,Wicklow,2023,4,2023 Q4,4.50,Republic of Ireland,False,361.0,412598.55,-1.032489,-10.216156,-5.532489,-14.716156
1656,Wicklow,2024,1,2024 Q1,3.47,Republic of Ireland,False,281.0,433852.05,5.151133,4.680364,1.681133,1.210364
1657,Wicklow,2024,2,2024 Q2,2.47,Republic of Ireland,False,307.0,395364.65,-8.871089,-9.879610,-11.341089,-12.349610
1658,Wicklow,2024,3,2024 Q3,1.53,Republic of Ireland,False,375.0,451250.53,14.135275,8.238726,12.605275,6.708726
1659,Wicklow,2024,4,2024 Q4,1.03,Republic of Ireland,False,428.0,438714.86,-2.777985,6.329714,-3.807985,5.299714
1660,Wicklow,2025,1,2025 Q1,1.90,Republic of Ireland,False,273.0,477255.01,8.784783,10.004092,6.884783,8.104092
1661,Wicklow,2025,2,2025 Q2,1.90,Republic of Ireland,False,288.0,456471.41,-4.354821,15.455798,-6.254821,13.555798
1662,Wicklow,2025,3,2025 Q3,2.13,Republic of Ireland,False,343.0,521350.59,14.213197,15.534621,12.083197,13.404621
1663,Wicklow,2025,4,2025 Q4,3.05,Republic of Ireland,False,127.0,457443.51,-12.257986,4.268980,-15.307986,1.218980